/** R7 scheme-freshness monitor, surfaced to users.
 *
 * `freshness.json` is a build-time condensation of the newest monitor report
 * (data/freshness/report-*.json): when every myScheme-sourced page was last
 * re-fetched and diffed against the committed corpus, and which schemes
 * drifted. Regenerated by scripts/generate_scheme_data.py; null when no
 * monitor run has been committed yet.
 */

import freshness from "@/lib/data/freshness.json";
import type { SchemeData } from "@/lib/schemes";

export interface SchemeDrift {
  needs_review: boolean;
  sections: string[];
}

interface FreshnessSummary {
  generated_at: string;
  schemes_checked: number;
  fetch_failures: string[];
  changed: Record<string, SchemeDrift>;
}

export const FRESHNESS: FreshnessSummary | null =
  freshness as FreshnessSummary | null;

/** Date (YYYY-MM-DD) of the last monitor run, or null before the first run. */
export const LAST_CHECKED = FRESHNESS ? FRESHNESS.generated_at.slice(0, 10) : null;

/** Schemes whose live official page drifted from the audited corpus text. */
export const CHANGED_COUNT = FRESHNESS
  ? Object.keys(FRESHNESS.changed).length
  : 0;

/** Whether the monitor's last run actually verified this scheme: it must be
 * myScheme-sourced (the 2 PDF-sourced docs aren't covered) and its re-fetch
 * must not have failed. */
export function wasChecked(scheme: SchemeData): boolean {
  return (
    FRESHNESS !== null &&
    scheme.page_url.includes("myscheme.gov.in") &&
    !FRESHNESS.fetch_failures.includes(scheme.scheme_id)
  );
}

/** Drift details for one scheme, or null if its source text is unchanged. */
export function getDrift(schemeId: string): SchemeDrift | null {
  return FRESHNESS?.changed[schemeId] ?? null;
}
