/** Typed access to the static scheme catalog (web/lib/data/schemes.json,
 *  generated by scripts/generate_scheme_data.py from the committed corpus). */

import data from "./data/schemes.json";

export interface SchemeRule {
  id: string;
  kind: "require" | "exclude";
  clause: string;
  source_url: string;
}

export interface SchemeData {
  scheme_id: string;
  short_name: string;
  name: string;
  category: string;
  ministry: string;
  page_url: string;
  references: { title: string; url: string }[];
  fetched_at: string | null;
  benefit_snippet: string;
  sections: Partial<
    Record<"details" | "benefits" | "eligibility" | "exclusions" | "application" | "documents", string>
  >;
  rules: SchemeRule[];
  /** Applicant is not an individual — the eligibility check can never apply.
   * Distinct from "coming soon" (rules pending review). */
  out_of_scope?: boolean;
  out_of_scope_reason?: string;
}

export const SCHEMES = data as SchemeData[];

export const CATEGORY_LABELS: Record<string, string> = {
  farmers: "Farming",
  pension: "Pensions",
  insurance: "Insurance",
  health: "Health",
  housing: "Housing",
  education: "Education",
  livelihood: "Livelihood",
  household: "Household",
  savings: "Savings",
};

/** Hand-curated audiences for the catalog filter — who a scheme is chiefly for. */
export const AUDIENCE_LABELS: Record<string, string> = {
  women: "Women & daughters",
  farmers: "Farmers",
  workers: "Workers & vendors",
  students: "Students",
  seniors: "Older adults",
  disability: "Persons with disabilities",
  families: "Low-income families",
};

const AUDIENCES: Record<string, string[]> = {
  "sukanya-samriddhi": ["women"],
  ignwps: ["women", "seniors"],
  pmuy: ["women", "families"],
  "pm-kisan": ["farmers"],
  pmfby: ["farmers"],
  "pm-svanidhi": ["workers"],
  pmv: ["workers"],
  pmsby: ["workers", "families"],
  pmjjby: ["workers", "families"],
  apy: ["workers"],
  "pms-sc": ["students"],
  "nsap-ignoaps": ["seniors"],
  igndps: ["disability"],
  "ab-pmjay": ["families"],
  "pmay-g": ["families"],
};

export function audiencesOf(schemeId: string): string[] {
  return AUDIENCES[schemeId] ?? [];
}

export function getScheme(schemeId: string): SchemeData | undefined {
  return SCHEMES.find((s) => s.scheme_id === schemeId);
}

export const CATEGORIES = [...new Set(SCHEMES.map((s) => s.category))].sort();
